package ca.uwaterloo.cs451.a3;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.FSDataInputStream;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.BytesWritable;
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.MapFile;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.io.WritableUtils;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;
import org.kohsuke.args4j.CmdLineException;
import org.kohsuke.args4j.CmdLineParser;
import org.kohsuke.args4j.Option;
import org.kohsuke.args4j.ParserProperties;
import tl.lin.data.array.ArrayListWritable;
import tl.lin.data.pair.PairOfInts;
import tl.lin.data.pair.PairOfWritables;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Set;
import java.util.Stack;
import java.util.TreeSet;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.util.ArrayList;
import java.util.List;

public class BooleanRetrievalCompressed extends Configured implements Tool {
  private List<MapFile.Reader> indexes; // Access to the inverted indexing (postings list)
  private FSDataInputStream collection; // Access to the file with documents 
  private Stack<Set<Integer>> stack; // Stack to store the docIDs while evaluating the query (only stores integers, not terms)

  private BooleanRetrievalCompressed() {}

  private void initialize(String indexPath, String collectionPath, FileSystem fs) throws IOException {
    indexes = new ArrayList<>(); // Open files generated by MapReduce
    collection = fs.open(new Path(collectionPath)); // Open doc
    stack = new Stack<>(); // Creates empty stack
  
    // Load all partitions generated (part-r-000*)
    int partitionNum = 0;
    while (true){
        Path partitionPath = new Path(indexPath + "/part-r-" + String.format("%05d", partitionNum));
        if (fs.exists(partitionPath)){
            indexes.add(new MapFile.Reader(partitionPath, fs.getConf()));
            partitionNum++;
        } else {
            // If there is no more partitions files
            break;
        }
    }
    System.out.println("Loaded" + indexes.size() + " index partitions.");
  }


  private void runQuery(String q) throws IOException {
    String[] terms = q.split("\\s+"); // Convert query in list splitted by spaces

    for (String t : terms) {
      if (t.equals("AND")) {
        performAND();
      } else if (t.equals("OR")) {
        performOR();
      } else {
        pushTerm(t);
      }
    }

    Set<Integer> set = stack.pop();

    // Print result 
    for (Integer i : set) {
      String line = fetchLine(i);
      System.out.println(i + "\t" + line);
    }
  }

    // Methods for the query

  private void pushTerm(String term) throws IOException {
    stack.push(fetchDocumentSet(term)); // pushes the list of docIDs of that term into the stack
  }

  private void performAND() {
    Set<Integer> s1 = stack.pop();
    Set<Integer> s2 = stack.pop();

    Set<Integer> sn = new TreeSet<>();

    for (int n : s1) {
      if (s2.contains(n)) {
        sn.add(n);
      }
    }

    stack.push(sn);
  }


  private void performOR() {
    Set<Integer> s1 = stack.pop();
    Set<Integer> s2 = stack.pop();

    Set<Integer> sn = new TreeSet<>();

    for (int n : s1) {
      sn.add(n);
    }

    for (int n : s2) {
      sn.add(n);
    }

    stack.push(sn);
  }


    // Gets the index list of the term and gets only docsIDs
  private Set<Integer> fetchDocumentSet(String term) throws IOException {
    Set<Integer> set = new TreeSet<>();

    for (PairOfInts pair : fetchPostings(term)) {
      set.add(pair.getLeftElement());
    }

    return set;
  }


    // Decompress postings & Look for the term (key) in the index list
  private List<PairOfInts> fetchPostings(String term) throws IOException {
    List<PairOfInts> postings = new ArrayList<>(); // Pairs of (docID, frequency)
    Text key = new Text();
    PairOfWritables<IntWritable, BytesWritable> value = new PairOfWritables<>();

    // Search in every partition
    for (MapFile.Reader index : indexes) {
        value = new PairOfWritables<>();
        if (index.get(key, value) != null){
            // Decompress (all the way around as we didi in BuildInvertedIndexCompressed)
            BytesWritable bytes = value.getRightElement();
            byte[] rawBytes = bytes.getBytes();
            int length = bytes.getLength();

            ByteArrayInputStream byteStream = new ByteArrayInputStream(rawBytes, 0, length);
            DataInputStream dataStream = new DataInputStream(byteStream);

            int docid = 0;
            while (dataStream.available() > 0) {
                int gap = WritableUtils.readVInt(dataStream);
                int tf = WritableUtils.readVInt(dataStream);
                docid += gap; // Reconstruct absolute docs IDs
                postings.add(new PairOfInts(docid, tf));
            }
            dataStream.close();
            break;
        }
    }
    
    return postings;
  }

  public String fetchLine(long offset) throws IOException {
    collection.seek(offset);
    BufferedReader reader = new BufferedReader(new InputStreamReader(collection));

    String d = reader.readLine();
    return d.length() > 80 ? d.substring(0, 80) + "..." : d;
  }

  private static final class Args {
    @Option(name = "-index", metaVar = "[path]", required = true, usage = "index path")
    String index;

    @Option(name = "-collection", metaVar = "[path]", required = true, usage = "collection path")
    String collection;

    @Option(name = "-query", metaVar = "[term]", required = true, usage = "query")
    String query;
  }

  /**
   * Runs this tool.
   */
  @Override
  public int run(String[] argv) throws Exception {
    final Args args = new Args();
    CmdLineParser parser = new CmdLineParser(args, ParserProperties.defaults().withUsageWidth(100));

    try {
      parser.parseArgument(argv);
    } catch (CmdLineException e) {
      System.err.println(e.getMessage());
      parser.printUsage(System.err);
      return -1;
    }

    if (args.collection.endsWith(".gz")) {
      System.out.println("gzipped collection is not seekable: use compressed version!");
      return -1;
    }

    FileSystem fs = FileSystem.get(new Configuration());

    initialize(args.index, args.collection, fs);

    System.out.println("Query: " + args.query);
    long startTime = System.currentTimeMillis();
    runQuery(args.query);
    System.out.println("\nquery completed in " + (System.currentTimeMillis() - startTime) + "ms");

    return 1;
  }

  /**
   * Dispatches command-line arguments to the tool via the {@code ToolRunner}.
   *
   * @param args command-line arguments
   * @throws Exception if tool encounters an exception
   */
  public static void main(String[] args) throws Exception {
    ToolRunner.run(new BooleanRetrievalCompressed(), args);
  }
}
